//! Character-by-character stdout verification tests
//!
//! This test module verifies that stdout content generated by tests
//! appears in log files character-for-character with no truncation,
//! corruption, or data loss.
//!
//! # Usage
//!
//! Run these tests via the wrapper script to capture output:
//! ```bash
//! ./bin/test-with-log.sh stdout_verification
//! ```
//!
//! The generated log file will be verified character-by-character against
//! the expected content.

mod output_capture_helpers;
use output_capture_helpers::*;
use std::fs;
use std::io::{self, Write};

#[test]
fn test_stdout_char_by_char_verification() {
    println!("=== Testing character-by-character stdout verification ===");

    // Generate predictable test output
    let test_messages = vec![
        "Verification test line 1",
        "Verification test line 2",
        "Verification test line 3 with special chars: @#$%",
    ];

    for msg in &test_messages {
        generate_stdout_message(msg);
    }

    println!("=== Character-by-character verification test completed ===");
}

#[test]
fn test_large_stdout_verification() {
    println!("=== Testing large stdout generation with verification ===");

    let config = LargeOutputConfig {
        target_size_bytes: 15_000, // ~15KB
        prefix: "VERIFY_LINE".to_string(),
        include_line_numbers: true,
    };

    let (total_bytes, line_count) = generate_and_print_large_stdout(&config);

    eprintln!(
        "VERIFICATION_METADATA: Generated {} lines (~{} bytes)",
        line_count, total_bytes
    );
    eprintln!("VERIFICATION_METADATA: Content is deterministic and verifiable");

    println!(
        "=== Large stdout verification test completed - {} bytes in {} lines ===",
        total_bytes, line_count
    );
}

#[test]
fn test_verification_in_memory() {
    println!("=== Testing in-memory verification logic ===");

    // This test demonstrates the verification logic without requiring
    // an external log file - it creates a temporary log for verification

    let expected_content = "Line 1\nLine 2\nLine 3\n";

    // Create a temporary log file
    let temp_dir = std::env::temp_dir();
    let log_path = temp_dir.join("test_in_memory_verify.log");

    // Simulate captured output
    let log_content = format!(
        "{}",
        expected_content
            .lines()
            .map(|line| format!("[STDOUT] {}", line))
            .collect::<Vec<_>>()
            .join("\n")
    );
    fs::write(&log_path, log_content).unwrap();

    // Verify character-by-character
    let result = verify_stdout_char_by_char(expected_content, &log_path).unwrap();

    assert!(result.passed, "In-memory verification should pass");
    assert_eq!(result.expected_chars, expected_content.chars().count());

    eprintln!("VERIFICATION_METADATA: In-memory verification passed");

    // Cleanup
    fs::remove_file(&log_path).ok();

    println!("=== In-memory verification test completed ===");
}

#[test]
fn test_verification_detects_mismatch() {
    println!("=== Testing verification mismatch detection ===");

    let expected_content = "Expected line 1\nExpected line 2\n";

    // Create a log with DIFFERENT content
    let temp_dir = std::env::temp_dir();
    let log_path = temp_dir.join("test_mismatch_detect.log");

    let mismatched_content = "[STDOUT] Expected line 1\n[STDOUT] Different line 2\n";
    fs::write(&log_path, mismatched_content).unwrap();

    let result = verify_stdout_char_by_char(expected_content, &log_path).unwrap();

    assert!(
        !result.passed,
        "Verification should fail for mismatched content"
    );
    assert!(result.first_mismatch_pos.is_some());
    assert!(result.first_mismatch_line.is_some());

    let failure_msg = result.failure_message();
    eprintln!("VERIFICATION_FAILURE: {}", failure_msg);

    // Cleanup
    fs::remove_file(&log_path).ok();

    println!("=== Mismatch detection test completed ===");
}

#[test]
fn test_unicode_and_special_chars() {
    println!("=== Testing unicode and special character verification ===");

    let unicode_content = "Hello, 世界! 🌍\nTab\there\tand\nnewlines\n";

    // Create log with unicode content
    let temp_dir = std::env::temp_dir();
    let log_path = temp_dir.join("test_unicode_verify.log");

    let log_lines = unicode_content
        .lines()
        .map(|line| format!("[STDOUT] {}", line))
        .collect::<Vec<_>>()
        .join("\n");
    fs::write(&log_path, log_lines).unwrap();

    let result = verify_stdout_char_by_char(unicode_content, &log_path).unwrap();

    assert!(result.passed, "Unicode verification should pass");
    assert_eq!(result.actual_chars, unicode_content.chars().count());

    eprintln!("VERIFICATION_METADATA: Unicode verification passed");

    // Cleanup
    fs::remove_file(&log_path).ok();

    println!("=== Unicode verification test completed ===");
}

#[test]
fn test_exact_content_preservation() {
    println!("=== Testing exact content preservation ===");

    let config = LargeOutputConfig {
        target_size_bytes: 5_000,
        prefix: "EXACT_PRESERVATION".to_string(),
        include_line_numbers: true,
    };

    let (bytes, lines, content) = generate_large_stdout(&config);

    // Generate to stdout for capture
    print!("{}", content);
    io::stdout().flush().unwrap();

    eprintln!(
        "VERIFICATION_METADATA: Content is deterministic - {} bytes, {} lines",
        bytes, lines
    );
    eprintln!("VERIFICATION_METADATA: Every character can be verified exactly");

    println!("=== Exact content preservation test completed ===");
}
