#!/bin/bash
# Performance Budget Test Integration
#
# This script orchestrates the full performance budget test:
# 1. Builds the daemon
# 2. Populates testrepo with load test data (if needed)
# 3. Starts the daemon with load-test projects
# 4. Runs synthetic load generation in the background
# 5. Runs Playwright UI performance tests against the loaded daemon
# 6. Reports results and exits with proper code
#
# Exit codes:
#   0 - All performance budgets passed
#   1 - One or more budget violations
#
# Plan reference: §6 Phase 6 deliverable 9
# Feeds into hoop-ttb.7.11 performance budget verification

set -euo pipefail

# Configuration
LOAD_SCALE="${LOAD_TEST_SCALE:-medium}"
PROJECTS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TESTREPO_DIR="$PROJECTS_ROOT/testrepo"
DAEMON_BIN="$PROJECTS_ROOT/target/release/hoop-daemon"
METRICS_PORT=8080
UI_PORT=5173

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Set scale parameters
case "$LOAD_SCALE" in
  full)
    NUM_PROJECTS=20
    WORKERS_PER_PROJECT=5
    BEADS_PER_WORKER=300
    ;;
  medium|*)
    NUM_PROJECTS=5
    WORKERS_PER_PROJECT=2
    BEADS_PER_WORKER=50
    ;;
esac

echo "=== Performance Budget Test ($LOAD_SCALE scale) ==="
echo "Projects: $NUM_PROJECTS"
echo "Workers per project: $WORKERS_PER_PROJECT"
echo "Beads per worker: $BEADS_PER_WORKER"
echo "Total beads: $((NUM_PROJECTS * WORKERS_PER_PROJECT * BEADS_PER_WORKER))"
echo ""

# Cleanup function
cleanup() {
  local exit_code=$?

  echo ""
  echo "=== Cleanup ==="

  # Kill background processes
  if [[ -n "${DAEMON_PID:-}" ]]; then
    echo "Stopping daemon (PID: $DAEMON_PID)..."
    kill "$DAEMON_PID" 2>/dev/null || true
    wait "$DAEMON_PID" 2>/dev/null || true
  fi

  if [[ -n "${LOAD_GEN_PID:-}" ]]; then
    echo "Stopping load generator (PID: $LOAD_GEN_PID)..."
    kill "$LOAD_GEN_PID" 2>/dev/null || true
    wait "$LOAD_GEN_PID" 2>/dev/null || true
  fi

  # Kill any stray hoop-daemon processes on our port
  pkill -f "hoop-daemon.*port $METRICS_PORT" 2>/dev/null || true

  echo "Cleanup complete"

  # Propagate exit code
  exit $exit_code
}

trap cleanup EXIT INT TERM

# Step 1: Check if daemon is built
echo "=== Step 1: Build Check ==="
if [[ ! -f "$DAEMON_BIN" ]]; then
  echo "Daemon not built at $DAEMON_BIN"
  echo "Building daemon..."
  cd "$PROJECTS_ROOT"
  cargo build --release
fi
echo "Daemon found at $DAEMON_BIN"
echo ""

# Step 2: Populate testrepo if needed
echo "=== Step 2: Testrepo Population ==="
LOAD_TEST_DIR="$TESTREPO_DIR/load-test-data"

if [[ ! -d "$LOAD_TEST_DIR/load-test-project-000" ]]; then
  echo "Populating testrepo with load test data..."
  "$PROJECTS_ROOT/hoop-daemon/tests/populate_testrepo_load.sh"
else
  echo "Testrepo already populated at $LOAD_TEST_DIR"
  # Verify we have enough projects
  EXISTING_PROJECTS=$(find "$LOAD_TEST_DIR" -maxdepth 1 -type d -name "load-test-project-*" | wc -l)
  echo "Found $EXISTING_PROJECTS projects"

  if [[ $EXISTING_PROJECTS -lt $NUM_PROJECTS ]]; then
    echo "Not enough projects for $LOAD_SCALE scale (need $NUM_PROJECTS, have $EXISTING_PROJECTS)"
    echo "Re-populating testrepo..."
    rm -rf "$LOAD_TEST_DIR"
    "$PROJECTS_ROOT/hoop-daemon/tests/populate_testrepo_load.sh"
  fi
fi
echo ""

# Step 3: Create projects.yaml for daemon
echo "=== Step 3: Daemon Configuration ==="
PROJECTS_YAML="$TESTREPO_DIR/projects-load-test.yaml"

cat > "$PROJECTS_YAML" <<EOF
# Load test projects configuration
# Auto-generated by run-performance-budget-test.sh

projects:
EOF

for i in $(seq 0 $((NUM_PROJECTS - 1))); do
  PROJECT_NAME=$(printf "load-test-project-%03d" "$i")
  cat >> "$PROJECTS_YAML" <<EOF
  - name: $PROJECT_NAME
    path: $LOAD_TEST_DIR/$PROJECT_NAME
EOF
done

echo "Created projects config at $PROJECTS_YAML"
echo ""

# Step 4: Start the daemon
echo "=== Step 4: Starting Daemon ==="
DAEMON_LOG="$PROJECTS_ROOT/target/daemon.log"
DAEMON_PID_FILE="$PROJECTS_ROOT/target/daemon.pid"

# Remove old log and pid
rm -f "$DAEMON_LOG" "$DAEMON_PID_FILE"

# Start daemon in background
cd "$PROJECTS_ROOT"
RUST_LOG=info "$DAEMON_BIN" \
  --projects "$PROJECTS_YAML" \
  --port "$METRICS_PORT" \
  > "$DAEMON_LOG" 2>&1 &

DAEMON_PID=$!
echo $DAEMON_PID > "$DAEMON_PID_FILE"
echo "Daemon started (PID: $DAEMON_PID)"
echo "Log: $DAEMON_LOG"
echo ""

# Wait for daemon to be ready
echo "Waiting for daemon to be ready..."
for i in {1..30}; do
  if curl -s "http://localhost:$METRICS_PORT/healthz" > /dev/null 2>&1; then
    echo "Daemon is ready!"
    break
  fi
  if [[ $i -eq 30 ]]; then
    echo "Timed out waiting for daemon"
    cat "$DAEMON_LOG"
    exit 1
  fi
  sleep 1
done
echo ""

# Step 5: Start load generation
echo "=== Step 5: Load Generation ==="

# Create a simple load generator script
LOAD_GEN_SCRIPT="$PROJECTS_ROOT/target/load-gen.sh"
cat > "$LOAD_GEN_SCRIPT" <<'EOFSCRIPT'
#!/bin/bash
# Simple load generator - makes concurrent API requests to the daemon

set -euo pipefail

BASE_URL="${1:-http://localhost:8080}"
DURATION="${2:-60}"
CONCURRENT="${3:-10}"

echo "Load generator: $CONCURRENT concurrent requests for ${DURATION}s"

END_TIME=$(($(date +%s) + DURATION))

while [[ $(date +%s) -lt $END_TIME ]]; do
  for i in $(seq 1 $CONCURRENT); do
    (
      curl -s "$BASE_URL/healthz" > /dev/null 2>&1 || true
      curl -s "$BASE_URL/api/beads?limit=10" > /dev/null 2>&1 || true
      curl -s "$BASE_URL/api/capacity" > /dev/null 2>&1 || true
    ) &
  done
  wait
  sleep 0.1
done

echo "Load generation complete"
EOFSCRIPT

chmod +x "$LOAD_GEN_SCRIPT"

# Run load generator in background
echo "Starting load generator (will run for 2 minutes)..."
"$LOAD_GEN_SCRIPT" "http://localhost:$METRICS_PORT" "120" "$((NUM_PROJECTS * WORKERS_PER_PROJECT))" \
  > "$PROJECTS_ROOT/target/load-gen.log" 2>&1 &

LOAD_GEN_PID=$!
echo "Load generator started (PID: $LOAD_GEN_PID)"
echo ""

# Step 6: Wait for load to stabilize
echo "=== Step 6: Stabilization ==="
echo "Waiting 5 seconds for load to stabilize..."
sleep 5
echo ""

# Step 7: Run Playwright performance tests
echo "=== Step 7: Playwright Performance Tests ==="
cd "$PROJECTS_ROOT/hoop-ui/web"

# Set environment for Playwright
export HOOP_LOAD_TEST_RUNNING=1
export LOAD_TEST_SCALE="$LOAD_SCALE"
export CI=true

echo "Running performance budget tests..."
if pnpm test:e2e performance-budget.spec.ts; then
  PLAYWRIGHT_RESULT=0
  echo -e "${GREEN}✓ Playwright performance tests passed${NC}"
else
  PLAYWRIGHT_RESULT=1
  echo -e "${RED}✗ Playwright performance tests failed${NC}"
fi
echo ""

# Step 8: Collect metrics
echo "=== Step 8: Metrics Collection ==="

# Get memory usage from daemon
if [[ -f "/proc/$DAEMON_PID/status" ]]; then
  DAEMON_RSS_KB=$(grep VmRSS "/proc/$DAEMON_PID/status" | awk '{print $2}')
  DAEMON_RSS_MB=$((DAEMON_RSS_KB / 1024))
  echo "Daemon RSS Memory: ${DAEMON_RSS_MB}MB"

  # Check against 4GB budget
  if [[ $DAEMON_RSS_MB -gt 4096 ]]; then
    echo -e "${RED}✗ Memory budget exceeded: ${DAEMON_RSS_MB}MB > 4096MB${NC}"
    MEMORY_RESULT=1
  else
    echo -e "${GREEN}✓ Memory budget satisfied: ${DAEMON_RSS_MB}MB < 4096MB${NC}"
    MEMORY_RESULT=0
  fi
else
  echo "Warning: Could not read daemon memory (not Linux?)"
  MEMORY_RESULT=0
fi

# Get sample API latency
echo "Testing API latency..."
API_LATENCIES=()
for i in {1..10}; do
  LATENCY=$(curl -s -o /dev/null -w '%{time_total}' "http://localhost:$METRICS_PORT/healthz")
  LATENCY_MS=$(echo "$LATENCY * 1000" | bc)
  API_LATENCIES+=("$LATENCY_MS")
done

# Calculate average
SUM=0
for lat in "${API_LATENCIES[@]}"; do
  SUM=$(echo "$SUM + $lat" | bc)
done
AVG_LATENCY=$(echo "scale=2; $SUM / ${#API_LATENCIES[@]}" | bc)
echo "Average API latency: ${AVG_LATENCY}ms"

# Check against 500ms budget
if (( $(echo "$AVG_LATENCY > 500" | bc -l) )); then
  echo -e "${RED}✗ API latency budget exceeded: ${AVG_LATENCY}ms > 500ms${NC}"
  API_RESULT=1
else
  echo -e "${GREEN}✓ API latency budget satisfied: ${AVG_LATENCY}ms < 500ms${NC}"
  API_RESULT=0
fi
echo ""

# Step 9: Summary
echo "=== Performance Budget Test Summary ==="
echo ""
echo "Results:"
echo "  Playwright UI Tests: $([ $PLAYWRIGHT_RESULT -eq 0 ] && echo 'PASS' || echo 'FAIL')"
echo "  Memory Budget (< 4GB): $([ $MEMORY_RESULT -eq 0 ] && echo 'PASS' || echo 'FAIL')"
echo "  API Latency (< 500ms): $([ $API_RESULT -eq 0 ] && echo 'PASS' || echo 'FAIL')"
echo ""

OVERALL_RESULT=$((PLAYWRIGHT_RESULT + MEMORY_RESULT + API_RESULT))

if [[ $OVERALL_RESULT -eq 0 ]]; then
  echo -e "${GREEN}=== ✓ ALL PERFORMANCE BUDGETS PASSED ===${NC}"
  exit 0
else
  echo -e "${RED}=== ✗ PERFORMANCE BUDGET VIOLATIONS DETECTED ===${NC}"
  echo "One or more budgets were exceeded. See details above."
  exit 1
fi
