/**
 * Schema drift test: Rust types ↔ TypeScript types round-trip parity (§3.5)
 *
 * This test validates that JSON fixtures generated by Rust can be parsed
 * by TypeScript types and round-trip back to the same JSON structure.
 *
 * Test fails if any field adds/removes mismatched between Rust and TS codegen.
 *
 * Fixtures are generated by hoop-schema/tests/schema_drift.rs
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'fs';
import { join } from 'path';
import type {
  WorkerData,
  BeadData,
  Bead,
  ConversationData,
  WebSocketEvent,
  ProjectsRegistry,
  AuditRow,
  Stitch,
  Pattern,
  HoopConfig,
} from './types.gen';

const FIXTURE_DIR = new URL('__fixtures__/schema/', import.meta.url).pathname;

// Read and parse a JSON fixture file
function loadFixture(name: string): unknown {
  const filePath = join(FIXTURE_DIR, `${name}.json`);
  if (!existsSync(filePath)) {
    throw new Error(`Fixture not found: ${filePath}`);
  }
  const content = readFileSync(filePath, 'utf-8');
  return JSON.parse(content);
}

// Deep compare two JSON values, ignoring formatting differences
function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;

  // Handle null/undefined
  if (a == null || b == null) return a === b;

  // Handle arrays
  if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) return false;
    return a.every((item, i) => deepEqual(item, b[i]));
  }

  // Handle objects
  if (typeof a === 'object' && typeof b === 'object') {
    const keysA = Object.keys(a as Record<string, unknown>);
    const keysB = Object.keys(b as Record<string, unknown>);
    if (keysA.length !== keysB.length) return false;
    return keysA.every(key =>
      deepEqual((a as Record<string, unknown>)[key], (b as Record<string, unknown>)[key])
    );
  }

  return false;
}

// Type-safe round-trip test for each fixture type
function testRoundTrip<T extends Record<string, unknown>>(
  fixtureName: string,
  typeGuard: (value: unknown) => value is T
): void {
  it(`${fixtureName}: Rust → JSON → TS parse → TS → JSON → Rust parse`, () => {
    // Step 1: Load JSON fixture (serialized by Rust)
    const originalJson = loadFixture(fixtureName);

    // Step 2: Parse with TypeScript type
    const parsed = originalJson as T;

    // Validate type guard passes
    expect(typeGuard(parsed)).toBe(true);

    // Step 3: Serialize back to JSON (as TypeScript would)
    const roundTripJson = JSON.parse(JSON.stringify(parsed));

    // Step 4: Verify deep equality
    // This ensures no fields are added or lost during the round-trip
    const match = deepEqual(originalJson, roundTripJson);
    expect(match).withContext(() => {
      const diff = [];
      if (!match) {
        diff.push('Original:', JSON.stringify(originalJson, null, 2));
        diff.push('Round-trip:', JSON.stringify(roundTripJson, null, 2));
      }
      return diff.join('\n');
    }).toBe(true);
  });
}

// Type guards for each schema type
function isWorkerData(value: unknown): value is WorkerData {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.worker === 'string' &&
    typeof v.state === 'object' &&
    typeof v.liveness === 'string' &&
    typeof v.last_heartbeat === 'string' &&
    typeof v.heartbeat_age_secs === 'number';
}

function isBeadData(value: unknown): value is BeadData {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.id === 'string' &&
    typeof v.title === 'string' &&
    typeof v.status === 'string' &&
    typeof v.priority === 'number' &&
    typeof v.created_at === 'string';
}

function isBead(value: unknown): value is Bead {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.id === 'string' &&
    typeof v.title === 'string' &&
    typeof v.status === 'string' &&
    typeof v.schema_version === 'string';
}

function isConversationData(value: unknown): value is ConversationData {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.id === 'string' &&
    typeof v.session_id === 'string' &&
    typeof v.provider === 'string' &&
    typeof v.kind === 'string';
}

function isWebSocketEvent(value: unknown): value is WebSocketEvent {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.type === 'string';
}

function isProjectsRegistry(value: unknown): value is ProjectsRegistry {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    Array.isArray(v.projects);
}

function isAuditRow(value: unknown): value is AuditRow {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.id === 'string' &&
    typeof v.ts === 'string' &&
    typeof v.actor === 'string' &&
    typeof v.kind === 'string' &&
    typeof v.schema_version === 'string';
}

function isStitch(value: unknown): value is Stitch {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.id === 'string' &&
    typeof v.project === 'string' &&
    typeof v.kind === 'string' &&
    typeof v.schema_version === 'string';
}

function isPattern(value: unknown): value is Pattern {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.id === 'string' &&
    typeof v.title === 'string' &&
    typeof v.status === 'string' &&
    typeof v.schema_version === 'string';
}

function isHoopConfig(value: unknown): value is HoopConfig {
  const v = value as Record<string, unknown>;
  return typeof v === 'object' && v !== null &&
    typeof v.schema_version === 'string';
}

describe('Schema drift: round-trip parity (§3.5)', () => {
  // Verify fixtures directory exists
  it('fixtures directory exists', () => {
    expect(existsSync(FIXTURE_DIR)).toBe(true);
  });

  // Verify index.json exists
  it('index.json exists', () => {
    expect(existsSync(join(FIXTURE_DIR, 'index.json'))).toBe(true);
  });

  // Test each fixture
  describe('WorkerData', () => {
    testRoundTrip('worker_data', isWorkerData);
  });

  describe('BeadData', () => {
    testRoundTrip('bead_data', isBeadData);
  });

  describe('Bead', () => {
    testRoundTrip('bead', isBead);
  });

  describe('ConversationData', () => {
    testRoundTrip('conversation_data', isConversationData);
  });

  describe('WebSocketEvent', () => {
    testRoundTrip('ws_event', isWebSocketEvent);
  });

  describe('ProjectsRegistry', () => {
    testRoundTrip('projects_registry', isProjectsRegistry);
  });

  describe('AuditRow', () => {
    testRoundTrip('audit_row', isAuditRow);
  });

  describe('Stitch', () => {
    testRoundTrip('stitch', isStitch);
  });

  describe('Pattern', () => {
    testRoundTrip('pattern', isPattern);
  });

  describe('HoopConfig', () => {
    testRoundTrip('hoop_config_minimal', isHoopConfig);
  });

  // Verify all fixtures are tested
  it('all fixtures in index.json have corresponding tests', () => {
    const index = JSON.parse(readFileSync(join(FIXTURE_DIR, 'index.json'), 'utf-8')) as Record<string, { file: string }>;
    const fixtureFiles = readdirSync(FIXTURE_DIR).filter(f => f.endsWith('.json') && f !== 'index.json');
    const testedFixtures = new Set([
      'worker_data',
      'bead_data',
      'bead',
      'conversation_data',
      'ws_event',
      'projects_registry',
      'audit_row',
      'stitch',
      'pattern',
      'hoop_config_minimal',
    ]);

    for (const [name, info] of Object.entries(index)) {
      expect(testedFixtures.has(name)).withContext(() =>
        `Fixture ${name} (${info.file}) is not tested`
      ).toBe(true);
    }
  });
});
