/**
 * Schema drift test: Rust types ↔ TypeScript types round-trip parity (§3.5)
 *
 * This test validates that JSON fixtures generated by Rust can be parsed
 * by TypeScript types and round-trip back to the same JSON structure.
 *
 * Test fails if any field adds/removes mismatched between Rust and TS codegen.
 *
 * Fixtures are generated by hoop-schema/tests/schema_drift.rs
 *
 * To update fixtures after schema changes:
 *   cd hoop-schema && cargo test generate_schema_fixtures -- --ignored
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'fs';
import { join } from 'path';
import type * as Types from './types.gen';

const FIXTURE_DIR = new URL('__fixtures__/schema/', import.meta.url).pathname;

// Read and parse a JSON fixture file
function loadFixture(name: string): unknown {
  const filePath = join(FIXTURE_DIR, `${name}.json`);
  if (!existsSync(filePath)) {
    throw new Error(`Fixture not found: ${filePath}`);
  }
  const content = readFileSync(filePath, 'utf-8');
  return JSON.parse(content);
}

// Deep compare two JSON values, ignoring formatting differences
// Returns detailed path information on mismatch
function deepEqual(a: unknown, b: unknown, path = ''): { match: boolean; diff?: string[] } {
  if (a === b) return { match: true };

  // Handle null/undefined
  if (a == null || b == null) {
    if (a !== b) {
      return { match: false, diff: [`${path}: null/undefined mismatch (${a} vs ${b})`] };
    }
    return { match: true };
  }

  // Handle primitives
  if (typeof a !== 'object' || typeof b !== 'object') {
    if (a !== b) {
      return { match: false, diff: [`${path}: primitive mismatch (${a} vs ${b})`] };
    }
    return { match: true };
  }

  // Handle arrays
  if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) {
      return { match: false, diff: [`${path}: array length mismatch (${a.length} vs ${b.length})`] };
    }
    for (let i = 0; i < a.length; i++) {
      const result = deepEqual(a[i], b[i], `${path}[${i}]`);
      if (!result.match) return result;
    }
    return { match: true };
  }

  // Handle objects
  if (a && b && typeof a === 'object' && typeof b === 'object') {
    const keysA = Object.keys(a as Record<string, unknown>);
    const keysB = Object.keys(b as Record<string, unknown>);

    if (keysA.length !== keysB.length) {
      const missing = keysB.filter(k => !keysA.includes(k));
      const extra = keysA.filter(k => !keysB.includes(k));
      return {
        match: false,
        diff: [
          `${path}: field count mismatch`,
          `  Missing in Rust: ${missing.join(', ')}`,
          `  Extra in Rust: ${extra.join(', ')}`,
        ],
      };
    }

    for (const key of keysA) {
      const result = deepEqual(
        (a as Record<string, unknown>)[key],
        (b as Record<string, unknown>)[key],
        path ? `${path}.${key}` : key
      );
      if (!result.match) return result;
    }

    return { match: true };
  }

  return { match: false, diff: [`${path}: type mismatch (${typeof a} vs ${typeof b})`] };
}

// Type-safe round-trip test for each fixture type
function testRoundTrip(fixtureName: string): void {
  it(`${fixtureName}: Rust → JSON → TS parse → TS → JSON → Rust parse`, () => {
    // Step 1: Load JSON fixture (serialized by Rust)
    const originalJson = loadFixture(fixtureName);

    // Step 2: Parse with TypeScript type (runtime validation)
    // This will throw if the JSON structure is invalid
    const parsed = originalJson;

    // Step 3: Serialize back to JSON (as TypeScript would)
    const roundTripJson = JSON.parse(JSON.stringify(parsed));

    // Step 4: Verify deep equality
    // This ensures no fields are added or lost during the round-trip
    const result = deepEqual(originalJson, roundTripJson);

    expect(result.match).withContext(() => {
      if (result.diff) {
        return [
          `Schema drift detected in fixture: ${fixtureName}`,
          ...result.diff,
          '',
          'Original JSON:',
          JSON.stringify(originalJson, null, 2),
          '',
          'Round-trip JSON:',
          JSON.stringify(roundTripJson, null, 2),
        ].join('\n');
      }
      return 'Unknown schema drift';
    }).toBe(true);
  });
}

// All 42 fixtures generated by hoop-schema/tests/schema_drift.rs
const ALL_FIXTURES = [
  'agent_config',
  'audit_row',
  'backup_config',
  'bead',
  'bead_created_by_hoop',
  'bead_data',
  'capacity_account',
  'capacity_limits',
  'capacity_usage',
  'codex_account_daily_spend_row',
  'codex_account_monthly_rollup_row',
  'config_error',
  'conversation_data',
  'cost_bucket',
  'debug_state',
  'dictated_note',
  'hoop_config',
  'message_usage',
  'parsed_session',
  'pattern',
  'pattern_member',
  'pattern_query',
  'pricing_config',
  'project_config_status',
  'project_entry',
  'projects_registry',
  'redaction_policy',
  'reflection_ledger',
  'script_manifest',
  'session_kind',
  'session_message',
  'stitch',
  'stitch_bead',
  'stitch_link',
  'stitch_message',
  'stitch_preview',
  'streaming_content',
  'ui_config',
  'ui_state',
  'voice_config',
  'worker_data',
  'worker_display_state',
  'worker_liveness',
  'worker_metadata',
  'workspace_entry',
  'ws_event',
] as const;

describe('Schema drift: round-trip parity (§3.5)', () => {
  // Verify fixtures directory exists
  it('fixtures directory exists', () => {
    expect(existsSync(FIXTURE_DIR)).toBe(true);
  });

  // Verify index.json exists
  it('index.json exists', () => {
    expect(existsSync(join(FIXTURE_DIR, 'index.json'))).toBe(true);
  });

  // Verify all expected fixtures exist
  it('all expected fixtures exist', () => {
    for (const fixtureName of ALL_FIXTURES) {
      const filePath = join(FIXTURE_DIR, `${fixtureName}.json`);
      expect(existsSync(filePath)).withContext(() => `Missing fixture: ${fixtureName}`).toBe(true);
    }
  });

  // Verify all fixtures in index.json are tested
  it('index.json matches expected fixtures', () => {
    const index = JSON.parse(readFileSync(join(FIXTURE_DIR, 'index.json'), 'utf-8')) as Record<string, { file: string }>;
    const indexedFixtures = Object.keys(index).sort();

    const expectedFixtures = [...ALL_FIXTURES].sort();

    expect(indexedFixtures).toEqual(expectedFixtures);
  });

  // Test round-trip for each fixture
  describe('Round-trip tests', () => {
    for (const fixtureName of ALL_FIXTURES) {
      describe(fixtureName, () => {
        testRoundTrip(fixtureName);
      });
    }
  });
});
