/**
 * Schema drift test: Rust types ↔ TypeScript types round-trip parity (§3.5)
 *
 * This test validates that JSON fixtures generated by Rust can be parsed
 * by TypeScript types and round-trip back to the same JSON structure.
 *
 * Test fails if any field adds/removes mismatched between Rust and TS codegen.
 *
 * Fixtures are generated by hoop-schema/tests/schema_drift.rs
 *
 * To update fixtures after schema changes:
 *   cd hoop-schema && cargo test generate_schema_fixtures -- --ignored
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'fs';
import { join } from 'path';
import type * as Types from './types.gen';

const FIXTURE_DIR = new URL('__fixtures__/schema/', import.meta.url).pathname;

// Read and parse a JSON fixture file
function loadFixture(name: string): unknown {
  const filePath = join(FIXTURE_DIR, `${name}.json`);
  if (!existsSync(filePath)) {
    throw new Error(`Fixture not found: ${filePath}`);
  }
  const content = readFileSync(filePath, 'utf-8');
  return JSON.parse(content);
}

// Deep compare two JSON values, ignoring formatting differences
// Returns detailed path information on mismatch
function deepEqual(a: unknown, b: unknown, path = ''): { match: boolean; diff?: string[] } {
  if (a === b) return { match: true };

  // Handle null/undefined
  if (a == null || b == null) {
    if (a !== b) {
      return { match: false, diff: [`${path}: null/undefined mismatch (${a} vs ${b})`] };
    }
    return { match: true };
  }

  // Handle primitives
  if (typeof a !== 'object' || typeof b !== 'object') {
    if (a !== b) {
      return { match: false, diff: [`${path}: primitive mismatch (${a} vs ${b})`] };
    }
    return { match: true };
  }

  // Handle arrays
  if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) {
      return { match: false, diff: [`${path}: array length mismatch (${a.length} vs ${b.length})`] };
    }
    for (let i = 0; i < a.length; i++) {
      const result = deepEqual(a[i], b[i], `${path}[${i}]`);
      if (!result.match) return result;
    }
    return { match: true };
  }

  // Handle objects
  if (a && b && typeof a === 'object' && typeof b === 'object') {
    const keysA = Object.keys(a as Record<string, unknown>);
    const keysB = Object.keys(b as Record<string, unknown>);

    if (keysA.length !== keysB.length) {
      const missing = keysB.filter(k => !keysA.includes(k));
      const extra = keysA.filter(k => !keysB.includes(k));
      return {
        match: false,
        diff: [
          `${path}: field count mismatch`,
          `  Missing in Rust: ${missing.join(', ')}`,
          `  Extra in Rust: ${extra.join(', ')}`,
        ],
      };
    }

    for (const key of keysA) {
      const result = deepEqual(
        (a as Record<string, unknown>)[key],
        (b as Record<string, unknown>)[key],
        path ? `${path}.${key}` : key
      );
      if (!result.match) return result;
    }

    return { match: true };
  }

  return { match: false, diff: [`${path}: type mismatch (${typeof a} vs ${typeof b})`] };
}

/**
 * Validate that a value matches the expected TypeScript type structure.
 * This checks for required fields to catch schema drift early.
 */
function validateTypeStructure(value: unknown, typeName: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  const has = (obj: unknown, prop: string): boolean => {
    return typeof obj === 'object' && obj !== null && prop in (obj as Record<string, unknown>);
  };

  switch (typeName) {
    case 'Bead':
      if (!has(value, 'id')) errors.push('Bead.id: missing required field');
      if (!has(value, 'title')) errors.push('Bead.title: missing required field');
      if (!has(value, 'status')) errors.push('Bead.status: missing required field');
      if (!has(value, 'schema_version')) errors.push('Bead.schema_version: missing required field');
      break;

    case 'Stitch':
      if (!has(value, 'id')) errors.push('Stitch.id: missing required field');
      if (!has(value, 'project')) errors.push('Stitch.project: missing required field');
      if (!has(value, 'kind')) errors.push('Stitch.kind: missing required field');
      if (!has(value, 'schema_version')) errors.push('Stitch.schema_version: missing required field');
      break;

    case 'HoopConfig':
      if (!has(value, 'schema_version')) errors.push('HoopConfig.schema_version: missing required field');
      break;

    case 'CapacityAccount':
      if (!has(value, 'id')) errors.push('CapacityAccount.id: missing required field');
      if (!has(value, 'adapter')) errors.push('CapacityAccount.adapter: missing required field');
      if (!has(value, 'limits')) errors.push('CapacityAccount.limits: missing required field');
      if (!has(value, 'usage')) errors.push('CapacityAccount.usage: missing required field');
      if (!has(value, 'schema_version')) errors.push('CapacityAccount.schema_version: missing required field');
      break;

    case 'AuditRow':
      if (!has(value, 'id')) errors.push('AuditRow.id: missing required field');
      if (!has(value, 'ts')) errors.push('AuditRow.ts: missing required field');
      if (!has(value, 'actor')) errors.push('AuditRow.actor: missing required field');
      if (!has(value, 'kind')) errors.push('AuditRow.kind: missing required field');
      if (!has(value, 'target')) errors.push('AuditRow.target: missing required field');
      break;

    case 'WorkerData':
      if (!has(value, 'worker')) errors.push('WorkerData.worker: missing required field');
      if (!has(value, 'state')) errors.push('WorkerData.state: missing required field');
      if (!has(value, 'liveness')) errors.push('WorkerData.liveness: missing required field');
      if (!has(value, 'last_heartbeat')) errors.push('WorkerData.last_heartbeat: missing required field');
      break;

    case 'Pattern':
      if (!has(value, 'id')) errors.push('Pattern.id: missing required field');
      if (!has(value, 'title')) errors.push('Pattern.title: missing required field');
      if (!has(value, 'status')) errors.push('Pattern.status: missing required field');
      if (!has(value, 'schema_version')) errors.push('Pattern.schema_version: missing required field');
      break;

    case 'UiState':
      if (!has(value, 'schema_version')) errors.push('UiState.schema_version: missing required field');
      break;

    case 'StitchBead':
      if (!has(value, 'stitch_id')) errors.push('StitchBead.stitch_id: missing required field');
      if (!has(value, 'bead_id')) errors.push('StitchBead.bead_id: missing required field');
      if (!has(value, 'workspace')) errors.push('StitchBead.workspace: missing required field');
      if (!has(value, 'schema_version')) errors.push('StitchBead.schema_version: missing required field');
      break;

    case 'StitchLink':
      if (!has(value, 'from_stitch')) errors.push('StitchLink.from_stitch: missing required field');
      if (!has(value, 'to_stitch')) errors.push('StitchLink.to_stitch: missing required field');
      if (!has(value, 'kind')) errors.push('StitchLink.kind: missing required field');
      if (!has(value, 'schema_version')) errors.push('StitchLink.schema_version: missing required field');
      break;

    case 'StitchMessage':
      if (!has(value, 'id')) errors.push('StitchMessage.id: missing required field');
      if (!has(value, 'stitch_id')) errors.push('StitchMessage.stitch_id: missing required field');
      if (!has(value, 'ts')) errors.push('StitchMessage.ts: missing required field');
      if (!has(value, 'role')) errors.push('StitchMessage.role: missing required field');
      if (!has(value, 'content')) errors.push('StitchMessage.content: missing required field');
      if (!has(value, 'schema_version')) errors.push('StitchMessage.schema_version: missing required field');
      break;

    case 'PatternMember':
      if (!has(value, 'pattern_id')) errors.push('PatternMember.pattern_id: missing required field');
      if (!has(value, 'stitch_id')) errors.push('PatternMember.stitch_id: missing required field');
      if (!has(value, 'schema_version')) errors.push('PatternMember.schema_version: missing required field');
      break;

    case 'ReflectionLedger':
      if (!has(value, 'id')) errors.push('ReflectionLedger.id: missing required field');
      if (!has(value, 'scope')) errors.push('ReflectionLedger.scope: missing required field');
      if (!has(value, 'rule')) errors.push('ReflectionLedger.rule: missing required field');
      if (!has(value, 'status')) errors.push('ReflectionLedger.status: missing required field');
      if (!has(value, 'schema_version')) errors.push('ReflectionLedger.schema_version: missing required field');
      break;
  }

  return { valid: errors.length === 0, errors };
}

// Map fixture names to their expected TypeScript type names
const FIXTURE_TO_TYPE: Record<string, string> = {
  'bead': 'Bead',
  'stitch': 'Stitch',
  'hoop_config': 'HoopConfig',
  'capacity_account': 'CapacityAccount',
  'audit_row': 'AuditRow',
  'worker_data': 'WorkerData',
  'pattern': 'Pattern',
  'ui_state': 'UiState',
  'stitch_bead': 'StitchBead',
  'stitch_link': 'StitchLink',
  'stitch_message': 'StitchMessage',
  'stitch_preview': 'StitchPreview',
  'pattern_member': 'PatternMember',
  'pattern_query': 'PatternQuery',
  'reflection_ledger': 'ReflectionLedger',
  'dictated_note': 'DictatedNote',
};

// Type-safe round-trip test for each fixture type
function testRoundTrip(fixtureName: string): void {
  it(`${fixtureName}: Rust → JSON → TS parse → TS → JSON → Rust parse`, () => {
    // Step 1: Load JSON fixture (serialized by Rust)
    const originalJson = loadFixture(fixtureName);

    // Step 2: Validate structure matches TypeScript type
    const typeName = FIXTURE_TO_TYPE[fixtureName];
    if (typeName) {
      const validation = validateTypeStructure(originalJson, typeName);
      if (!validation.valid) {
        expect(validation.errors).toEqual([]);
      }
    }

    // Step 3: Serialize back to JSON (as TypeScript would)
    const roundTripJson = JSON.parse(JSON.stringify(originalJson));

    // Step 4: Verify deep equality
    // This ensures no fields are added or lost during the round-trip
    const result = deepEqual(originalJson, roundTripJson);

    expect(result.match).withContext(() => {
      if (result.diff) {
        return [
          `Schema drift detected in fixture: ${fixtureName}`,
          'Path: ' + (result.diff?.[0] || 'unknown'),
          ...result.diff.slice(1),
          '',
          'Original JSON:',
          JSON.stringify(originalJson, null, 2),
          '',
          'Round-trip JSON:',
          JSON.stringify(roundTripJson, null, 2),
        ].join('\n');
      }
      return 'Unknown schema drift';
    }).toBe(true);
  });
}

// All 42 fixtures generated by hoop-schema/tests/schema_drift.rs
const ALL_FIXTURES = [
  'agent_config',
  'audit_row',
  'backup_config',
  'bead',
  'bead_created_by_hoop',
  'bead_data',
  'capacity_account',
  'capacity_limits',
  'capacity_usage',
  'codex_account_daily_spend_row',
  'codex_account_monthly_rollup_row',
  'config_error',
  'conversation_data',
  'cost_bucket',
  'debug_state',
  'dictated_note',
  'hoop_config',
  'message_usage',
  'parsed_session',
  'pattern',
  'pattern_member',
  'pattern_query',
  'pricing_config',
  'project_config_status',
  'project_entry',
  'projects_registry',
  'redaction_policy',
  'reflection_ledger',
  'script_manifest',
  'session_kind',
  'session_message',
  'stitch',
  'stitch_bead',
  'stitch_link',
  'stitch_message',
  'stitch_preview',
  'streaming_content',
  'ui_config',
  'ui_state',
  'voice_config',
  'worker_data',
  'worker_display_state',
  'worker_liveness',
  'worker_metadata',
  'workspace_entry',
  'ws_event',
] as const;

describe('Schema drift: round-trip parity (§3.5)', () => {
  // Verify fixtures directory exists
  it('fixtures directory exists', () => {
    expect(existsSync(FIXTURE_DIR)).toBe(true);
  });

  // Verify index.json exists
  it('index.json exists', () => {
    expect(existsSync(join(FIXTURE_DIR, 'index.json'))).toBe(true);
  });

  // Verify all expected fixtures exist
  it('all expected fixtures exist', () => {
    for (const fixtureName of ALL_FIXTURES) {
      const filePath = join(FIXTURE_DIR, `${fixtureName}.json`);
      expect(existsSync(filePath)).withContext(() => `Missing fixture: ${fixtureName}`).toBe(true);
    }
  });

  // Verify all fixtures in index.json are tested
  it('index.json matches expected fixtures', () => {
    const index = JSON.parse(readFileSync(join(FIXTURE_DIR, 'index.json'), 'utf-8')) as Record<string, { file: string }>;
    const indexedFixtures = Object.keys(index).sort();

    const expectedFixtures = [...ALL_FIXTURES].sort();

    expect(indexedFixtures).toEqual(expectedFixtures);
  });

  // Test round-trip for each fixture
  describe('Round-trip tests', () => {
    for (const fixtureName of ALL_FIXTURES) {
      describe(fixtureName, () => {
        testRoundTrip(fixtureName);
      });
    }
  });
});
