/**
 * AUTO-GENERATED TypeScript types from JSON Schema
 *
 * Source: hoop-schema/schemas/
 * Generated by: scripts/codegen-types.mjs
 * Do not edit manually - regenerate with: pnpm run codegen
 *
 * Schema version: 1.0.0
 */

/**
 * Worker liveness state
 */
export type WorkerLiveness = "Live" | "Hung" | "Dead";


/**
 * Worker state for display (combines WorkerState with additional info)
 */
export interface WorkerDisplayState {
  state: "executing" | "idle" | "knot";
  /**
   * Bead ID (when executing)
   */
  bead?: string;
  /**
   * Adapter name (when executing)
   */
  adapter?: string;
  /**
   * Model name (when executing)
   */
  model?: string;
  /**
   * Last strand worked on (when idle)
   */
  last_strand?: string | null;
  /**
   * Reason for knot state (when knotted)
   */
  reason?: string;
  [k: string]: unknown;
}


/**
 * Worker metadata for worker sessions
 */
export interface WorkerMetadata {
  /**
   * Worker name
   */
  worker: string;
  /**
   * Bead ID
   */
  bead: string;
  /**
   * Strand name
   */
  strand?: string | null;
  [k: string]: unknown;
}


/**
 * Worker data sent to the frontend
 */
export interface WorkerData {
  /**
   * Worker name (NATO phonetic: alpha, bravo, etc.)
   */
  worker: string;
  state: {
    state: "executing" | "idle" | "knot";
    /**
     * Bead ID (when executing)
     */
    bead?: string;
    /**
     * Adapter name (when executing)
     */
    adapter?: string;
    /**
     * Model name (when executing)
     */
    model?: string;
    /**
     * Last strand worked on (when idle)
     */
    last_strand?: string | null;
    /**
     * Reason for knot state (when knotted)
     */
    reason?: string;
    [k: string]: unknown;
  };
  liveness: "Live" | "Hung" | "Dead";
  /**
   * ISO 8601 timestamp of last heartbeat
   */
  last_heartbeat: string;
  /**
   * Age of last heartbeat in seconds
   */
  heartbeat_age_secs: number;
  [k: string]: unknown;
}


/**
 * Token usage from a single message
 */
export interface MessageUsage {
  /**
   * Input tokens (prompt)
   */
  input_tokens: number;
  /**
   * Output tokens (completion)
   */
  output_tokens: number;
  /**
   * Cache read tokens (prompt cache hits)
   */
  cache_read_tokens: number;
  /**
   * Cache write tokens (new cache entries)
   */
  cache_write_tokens: number;
  [k: string]: unknown;
}


/**
 * Bead data sent to the frontend
 */
export interface BeadData {
  /**
   * Bead ID (e.g., hoop-ttb.1)
   */
  id: string;
  /**
   * Bead title
   */
  title: string;
  /**
   * Bead status
   */
  status: "open" | "closed";
  /**
   * Priority (0 = highest)
   */
  priority: number;
  /**
   * Issue type
   */
  issue_type: "task" | "bug" | "epic";
  /**
   * ISO 8601 timestamp
   */
  created_at: string;
  /**
   * ISO 8601 timestamp
   */
  updated_at: string;
  /**
   * Creator username
   */
  created_by: string;
  /**
   * List of dependent bead IDs
   */
  dependencies: string[];
  [k: string]: unknown;
}


/**
 * A tracking bead (issue/task) in the beads system
 */
export interface Bead {
  /**
   * Bead ID (e.g., hoop-ttb.1)
   */
  id: string;
  /**
   * Bead title
   */
  title: string;
  /**
   * Bead description
   */
  description?: string | null;
  /**
   * Bead status
   */
  status: "open" | "closed";
  /**
   * Priority (0 = highest)
   */
  priority: number;
  /**
   * Issue type
   */
  issue_type: "task" | "bug" | "epic" | "genesis" | "review" | "fix";
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Last update timestamp
   */
  updated_at: string;
  /**
   * Creator username
   */
  created_by: string;
  /**
   * List of dependent bead IDs
   */
  dependencies: string[];
  schema_version: string;
  [k: string]: unknown;
}


/**
 * Classification of a CLI session based on its prefix tag
 */
export type SessionKind = Worker | "dictated" | "ad_hoc" | "operator";

export interface Worker {
  /**
   * Worker name (NATO identifier)
   */
  worker: string;
  /**
   * Bead ID being processed
   */
  bead: string;
  /**
   * Strand name (pluck, explore, mend, etc.)
   */
  strand?: string | null;
}


/**
 * A single message in a CLI session transcript
 */
export interface SessionMessage {
  /**
   * Message role (user, assistant, system, tool)
   */
  role: string;
  /**
   * Message content (may be text or structured for tool use)
   */
  content: {
    [k: string]: unknown;
  };
  usage?: {
    /**
     * Input tokens (prompt)
     */
    input_tokens: number;
    /**
     * Output tokens (completion)
     */
    output_tokens: number;
    /**
     * Cache read tokens (prompt cache hits)
     */
    cache_read_tokens: number;
    /**
     * Cache write tokens (new cache entries)
     */
    cache_write_tokens: number;
    [k: string]: unknown;
  };
  /**
   * Message timestamp if available
   */
  timestamp?: string | null;
  [k: string]: unknown;
}


/**
 * A parsed CLI session with classification, messages, and metadata
 */
export interface ParsedSession {
  /**
   * Stable ID (UUID)
   */
  id: string;
  /**
   * Provider-native session ID
   */
  session_id: string;
  /**
   * CLI provider name
   */
  provider: string;
  /**
   * Session classification
   */
  kind: Worker | "dictated" | "ad_hoc" | "operator";
  /**
   * Working directory when session was created
   */
  cwd: string;
  /**
   * Session title
   */
  title: string;
  /**
   * Messages in the session
   */
  messages: {
    /**
     * Message role (user, assistant, system, tool)
     */
    role: string;
    /**
     * Message content (may be text or structured for tool use)
     */
    content: {
      [k: string]: unknown;
    };
    usage?: {
      /**
       * Input tokens (prompt)
       */
      input_tokens: number;
      /**
       * Output tokens (completion)
       */
      output_tokens: number;
      /**
       * Cache read tokens (prompt cache hits)
       */
      cache_read_tokens: number;
      /**
       * Cache write tokens (new cache entries)
       */
      cache_write_tokens: number;
      [k: string]: unknown;
    };
    /**
     * Message timestamp if available
     */
    timestamp?: string | null;
    [k: string]: unknown;
  }[];
  /**
   * Aggregate token usage
   */
  total_usage: {
    [k: string]: unknown;
  };
  /**
   * Session start time
   */
  created_at: string;
  /**
   * Last activity time
   */
  updated_at: string;
  /**
   * Whether the session is complete
   */
  complete: boolean;
  /**
   * Path to the session file on disk
   */
  file_path: string;
  [k: string]: unknown;
}
export interface Worker {
  /**
   * Worker name (NATO identifier)
   */
  worker: string;
  /**
   * Bead ID being processed
   */
  bead: string;
  /**
   * Strand name (pluck, explore, mend, etc.)
   */
  strand?: string | null;
}


/**
 * Conversation/session data sent to the frontend
 */
export interface ConversationData {
  /**
   * Stable UI ID (UUID)
   */
  id: string;
  /**
   * Provider-native session ID
   */
  session_id: string;
  /**
   * Provider name
   */
  provider: "claude" | "codex" | "gemini" | "opencode" | "aider";
  /**
   * Session classification
   */
  kind: "operator" | "dictated" | "worker" | "ad-hoc";
  worker_metadata?: {
    /**
     * Worker name
     */
    worker: string;
    /**
     * Bead ID
     */
    bead: string;
    /**
     * Strand name
     */
    strand?: string | null;
    [k: string]: unknown;
  };
  /**
   * Working directory when session was created
   */
  cwd: string;
  /**
   * Session title
   */
  title: string;
  messages: {
    /**
     * Message role (user, assistant, system, tool)
     */
    role: string;
    /**
     * Message content (may be text or structured for tool use)
     */
    content: {
      [k: string]: unknown;
    };
    usage?: {
      /**
       * Input tokens (prompt)
       */
      input_tokens: number;
      /**
       * Output tokens (completion)
       */
      output_tokens: number;
      /**
       * Cache read tokens (prompt cache hits)
       */
      cache_read_tokens: number;
      /**
       * Cache write tokens (new cache entries)
       */
      cache_write_tokens: number;
      [k: string]: unknown;
    };
    /**
     * Message timestamp if available
     */
    timestamp?: string | null;
    [k: string]: unknown;
  }[];
  /**
   * Total tokens used
   */
  total_tokens: number;
  created_at: string;
  updated_at: string;
  /**
   * Whether the session is complete (process exited)
   */
  complete: boolean;
  /**
   * Path to the session file on disk
   */
  file_path: string;
  [k: string]: unknown;
}


/**
 * Streaming content update
 */
export interface StreamingContent {
  /**
   * Conversation ID
   */
  conversation_id: string;
  /**
   * Content fragment
   */
  content: string;
  /**
   * Unix timestamp in milliseconds
   */
  timestamp: number;
  [k: string]: unknown;
}


/**
 * WebSocket events sent to connected clients
 */
export interface WebSocketEvent {
  type:
    | "worker_update"
    | "workers_snapshot"
    | "beads_snapshot"
    | "conversations_snapshot"
    | "conversation_update"
    | "streaming_content"
    | "config_status";
  worker?: {
    /**
     * Worker name (NATO phonetic: alpha, bravo, etc.)
     */
    worker: string;
    state: {
      state: "executing" | "idle" | "knot";
      /**
       * Bead ID (when executing)
       */
      bead?: string;
      /**
       * Adapter name (when executing)
       */
      adapter?: string;
      /**
       * Model name (when executing)
       */
      model?: string;
      /**
       * Last strand worked on (when idle)
       */
      last_strand?: string | null;
      /**
       * Reason for knot state (when knotted)
       */
      reason?: string;
      [k: string]: unknown;
    };
    liveness: "Live" | "Hung" | "Dead";
    /**
     * ISO 8601 timestamp of last heartbeat
     */
    last_heartbeat: string;
    /**
     * Age of last heartbeat in seconds
     */
    heartbeat_age_secs: number;
    [k: string]: unknown;
  };
  workers?: unknown[];
  beads?: {
    /**
     * Bead ID (e.g., hoop-ttb.1)
     */
    id: string;
    /**
     * Bead title
     */
    title: string;
    /**
     * Bead status
     */
    status: "open" | "closed";
    /**
     * Priority (0 = highest)
     */
    priority: number;
    /**
     * Issue type
     */
    issue_type: "task" | "bug" | "epic";
    /**
     * ISO 8601 timestamp
     */
    created_at: string;
    /**
     * ISO 8601 timestamp
     */
    updated_at: string;
    /**
     * Creator username
     */
    created_by: string;
    /**
     * List of dependent bead IDs
     */
    dependencies: string[];
    [k: string]: unknown;
  }[];
  conversations?: {
    /**
     * Stable UI ID (UUID)
     */
    id: string;
    /**
     * Provider-native session ID
     */
    session_id: string;
    /**
     * Provider name
     */
    provider: "claude" | "codex" | "gemini" | "opencode" | "aider";
    /**
     * Session classification
     */
    kind: "operator" | "dictated" | "worker" | "ad-hoc";
    worker_metadata?: {
      /**
       * Worker name
       */
      worker: string;
      /**
       * Bead ID
       */
      bead: string;
      /**
       * Strand name
       */
      strand?: string | null;
      [k: string]: unknown;
    };
    /**
     * Working directory when session was created
     */
    cwd: string;
    /**
     * Session title
     */
    title: string;
    messages: {
      /**
       * Message role (user, assistant, system, tool)
       */
      role: string;
      /**
       * Message content (may be text or structured for tool use)
       */
      content: {
        [k: string]: unknown;
      };
      usage?: {
        /**
         * Input tokens (prompt)
         */
        input_tokens: number;
        /**
         * Output tokens (completion)
         */
        output_tokens: number;
        /**
         * Cache read tokens (prompt cache hits)
         */
        cache_read_tokens: number;
        /**
         * Cache write tokens (new cache entries)
         */
        cache_write_tokens: number;
        [k: string]: unknown;
      };
      /**
       * Message timestamp if available
       */
      timestamp?: string | null;
      [k: string]: unknown;
    }[];
    /**
     * Total tokens used
     */
    total_tokens: number;
    created_at: string;
    updated_at: string;
    /**
     * Whether the session is complete (process exited)
     */
    complete: boolean;
    /**
     * Path to the session file on disk
     */
    file_path: string;
    [k: string]: unknown;
  }[];
  conversation?: unknown;
  streaming?: {
    /**
     * Conversation ID
     */
    conversation_id: string;
    /**
     * Content fragment
     */
    content: string;
    /**
     * Unix timestamp in milliseconds
     */
    timestamp: number;
    [k: string]: unknown;
  };
  config_status?: {
    /**
     * True if the configuration is valid, false if there was a parse error
     */
    valid: boolean;
    /**
     * Error details if the configuration is invalid
     */
    error?: {
      /**
       * Human-readable error message
       */
      message: string;
      /**
       * Line number where the error occurred (1-indexed)
       */
      line: number;
      /**
       * Column number where the error occurred (1-indexed)
       */
      col: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}


/**
 * UI state persisted across sessions
 */
export interface UiState {
  /**
   * Currently active project
   */
  active_project?: string | null;
  /**
   * Currently active stitch
   */
  active_stitch?: string | null;
  /**
   * Sidebar width in pixels
   */
  sidebar_width?: number;
  panel_layout?: {
    fleet_visible?: boolean;
    beads_visible?: boolean;
    conversations_visible?: boolean;
    patterns_visible?: boolean;
    [k: string]: unknown;
  };
  filters?: {
    bead_status?: ("open" | "closed")[];
    stitch_kind?: ("operator" | "dictated" | "worker" | "ad-hoc")[];
    show_archived?: boolean;
    [k: string]: unknown;
  };
  theme?: "light" | "dark" | "auto";
  schema_version: string;
  [k: string]: unknown;
}


/**
 * Capacity limits for an adapter account
 */
export interface CapacityLimits {
  /**
   * Token limit per 5-hour window (Claude-specific)
   */
  tokens_per_5h?: number | null;
  /**
   * Token limit per 7-day window (Claude-specific)
   */
  tokens_per_7d?: number | null;
  /**
   * Request limit per day
   */
  requests_per_day?: number | null;
  /**
   * Spend limit per day in USD
   */
  spend_usd_per_day?: number | null;
  /**
   * Concurrent request limit
   */
  concurrent_requests?: number | null;
  [k: string]: unknown;
}


/**
 * Current capacity usage for an adapter account
 */
export interface CapacityUsage {
  /**
   * Tokens used in current 5-hour window
   */
  tokens_5h: number;
  /**
   * Tokens used in current 7-day window
   */
  tokens_7d: number;
  /**
   * Requests made today
   */
  requests_today: number;
  /**
   * USD spent today
   */
  spend_usd_today: number;
  /**
   * Currently active requests
   */
  active_requests?: number;
  [k: string]: unknown;
}


/**
 * Capacity account for tracking adapter usage limits
 */
export interface CapacityAccount {
  /**
   * Capacity account ID
   */
  id: string;
  /**
   * Adapter name
   */
  adapter: "claude" | "codex" | "opencode" | "gemini" | "zai";
  /**
   * Provider account identifier
   */
  account_id: string;
  limits: {
    /**
     * Token limit per 5-hour window (Claude-specific)
     */
    tokens_per_5h?: number | null;
    /**
     * Token limit per 7-day window (Claude-specific)
     */
    tokens_per_7d?: number | null;
    /**
     * Request limit per day
     */
    requests_per_day?: number | null;
    /**
     * Spend limit per day in USD
     */
    spend_usd_per_day?: number | null;
    /**
     * Concurrent request limit
     */
    concurrent_requests?: number | null;
    [k: string]: unknown;
  };
  usage: {
    /**
     * Tokens used in current 5-hour window
     */
    tokens_5h: number;
    /**
     * Tokens used in current 7-day window
     */
    tokens_7d: number;
    /**
     * Requests made today
     */
    requests_today: number;
    /**
     * USD spent today
     */
    spend_usd_today: number;
    /**
     * Currently active requests
     */
    active_requests?: number;
    [k: string]: unknown;
  };
  /**
   * Current window start time
   */
  window_start?: string;
  /**
   * Current window end time
   */
  window_end?: string;
  /**
   * Last update timestamp
   */
  updated_at: string;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * A workspace entry within a project
 */
export interface WorkspaceEntry {
  /**
   * Absolute path to the workspace
   */
  path: string;
  /**
   * Workspace role
   */
  role: "primary" | "manifests" | "source" | "secrets" | "docs";
  [k: string]: unknown;
}


/**
 * A single project entry in the registry
 */
export type ProjectEntry =
  | {
      /**
       * Project name
       */
      name: string;
      /**
       * Absolute path to the workspace (single-workspace shorthand)
       */
      path: string;
      /**
       * Optional label
       */
      label?: string;
      /**
       * Optional color hex code
       */
      color?: string;
      [k: string]: unknown;
    }
  | {
      /**
       * Project name
       */
      name: string;
      /**
       * Optional label
       */
      label?: string;
      /**
       * Optional color hex code
       */
      color?: string;
      workspaces: {
        /**
         * Absolute path to the workspace
         */
        path: string;
        /**
         * Workspace role
         */
        role: "primary" | "manifests" | "source" | "secrets" | "docs";
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    };


/**
 * Project registry structure for projects.yaml
 */
export interface ProjectsRegistry {
  projects: (
    | {
        /**
         * Project name
         */
        name: string;
        /**
         * Absolute path to the workspace (single-workspace shorthand)
         */
        path: string;
        /**
         * Optional label
         */
        label?: string;
        /**
         * Optional color hex code
         */
        color?: string;
        [k: string]: unknown;
      }
    | {
        /**
         * Project name
         */
        name: string;
        /**
         * Optional label
         */
        label?: string;
        /**
         * Optional color hex code
         */
        color?: string;
        workspaces: {
          /**
           * Absolute path to the workspace
           */
          path: string;
          /**
           * Workspace role
           */
          role: "primary" | "manifests" | "source" | "secrets" | "docs";
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      }
  )[];
  [k: string]: unknown;
}


/**
 * Human-interface agent configuration
 */
export interface AgentConfig {
  /**
   * Adapter selection
   */
  adapter?: "claude" | "codex" | "opencode" | "gemini" | "zai";
  /**
   * Model name (e.g., opus, sonnet, haiku)
   */
  model?: string;
  /**
   * Optional rate limit
   */
  rate_limit_requests_per_minute?: number;
  /**
   * Optional cost cap per session
   */
  cost_cap_per_session_usd?: number;
}


/**
 * S3-compatible backup configuration. Credentials are resolved from environment variables only — never stored in this file.
 */
export interface BackupConfig {
  /**
   * S3-compatible endpoint URL
   */
  endpoint: string;
  /**
   * Bucket name
   */
  bucket: string;
  /**
   * Key prefix for backup objects
   */
  prefix: string;
  /**
   * Cron schedule for automatic backups (default: daily at 04:00 UTC)
   */
  schedule?: string;
  /**
   * Number of days to retain backups before pruning
   */
  retention_days?: number;
  /**
   * Encrypt backups with age (requires HOOP_BACKUP_AGE_KEY env var)
   */
  encryption?: boolean;
}


/**
 * UI configuration
 */
export interface UiConfig {
  theme?: "light" | "dark" | "auto";
  default_project_sort?: "name" | "last_activity" | "worker_count";
  archive_after_days?: number;
}


/**
 * Voice/dictation configuration
 */
export interface VoiceConfig {
  /**
   * Path to Whisper model
   */
  whisper_model_path?: string;
  /**
   * Hotkey binding
   */
  hotkey?: string;
  max_recording_seconds?: number;
}


/**
 * Provider pricing configuration for cost calculation
 */
export interface PricingConfig {
  /**
   * Pricing per adapter
   */
  adapters?: {
    [k: string]: {
      models?: {
        [k: string]: {
          /**
           * Input price per million tokens (USD)
           */
          input_per_million: number;
          /**
           * Output price per million tokens (USD)
           */
          output_per_million: number;
          /**
           * Cache read price per million tokens (USD)
           */
          cache_read_per_million?: number;
          /**
           * Cache write price per million tokens (USD)
           */
          cache_write_per_million?: number;
        };
      };
      /**
       * Default model if not specified
       */
      default_model?: string;
    };
  };
}


/**
 * Aggregated cost bucket for a single day
 */
export interface CostBucket {
  /**
   * Bucket date (YYYY-MM-DD)
   */
  date: string;
  /**
   * Project name
   */
  project: string;
  /**
   * Adapter name (claude, codex, etc.)
   */
  adapter: string;
  /**
   * Model name (opus, sonnet, haiku, etc.)
   */
  model: string;
  /**
   * Strand name (pluck, explore, etc.), null if not applicable
   */
  strand: string | null;
  /**
   * Aggregate token usage
   */
  usage: {
    /**
     * Input tokens (prompt)
     */
    input_tokens: number;
    /**
     * Output tokens (completion)
     */
    output_tokens: number;
    /**
     * Cache read tokens (prompt cache hits)
     */
    cache_read_tokens: number;
    /**
     * Cache write tokens (new cache entries)
     */
    cache_write_tokens: number;
    [k: string]: unknown;
  };
  /**
   * Number of requests
   */
  request_count?: number;
  /**
   * Total cost in USD
   */
  cost_usd: number;
  [k: string]: unknown;
}


/**
 * HOOP daemon configuration from config.yml
 */
export interface HoopConfig {
  /**
   * Schema version for compatibility tracking (SemVer)
   */
  schema_version: string;
  agent?: {
    /**
     * Adapter selection
     */
    adapter?: "claude" | "codex" | "opencode" | "gemini" | "zai";
    /**
     * Model name (e.g., opus, sonnet, haiku)
     */
    model?: string;
    /**
     * Optional rate limit
     */
    rate_limit_requests_per_minute?: number;
    /**
     * Optional cost cap per session
     */
    cost_cap_per_session_usd?: number;
  };
  /**
   * Path to projects.yaml (default ~/.hoop/projects.yaml)
   */
  projects_file?: string;
  backup?: {
    /**
     * S3-compatible endpoint URL
     */
    endpoint: string;
    /**
     * Bucket name
     */
    bucket: string;
    /**
     * Key prefix for backup objects
     */
    prefix: string;
    /**
     * Cron schedule for automatic backups (default: daily at 04:00 UTC)
     */
    schedule?: string;
    /**
     * Number of days to retain backups before pruning
     */
    retention_days?: number;
    /**
     * Encrypt backups with age (requires HOOP_BACKUP_AGE_KEY env var)
     */
    encryption?: boolean;
  };
  ui?: {
    theme?: "light" | "dark" | "auto";
    default_project_sort?: "name" | "last_activity" | "worker_count";
    archive_after_days?: number;
  };
  voice?: {
    /**
     * Path to Whisper model
     */
    whisper_model_path?: string;
    /**
     * Hotkey binding
     */
    hotkey?: string;
    max_recording_seconds?: number;
  };
  agent_extensions?: {
    /**
     * Path to skills directory
     */
    skills?: string;
    /**
     * Path to scripts directory
     */
    scripts?: string;
    /**
     * Path to notes directory
     */
    notes?: string;
    /**
     * Path to prompts directory
     */
    prompts?: string;
  };
  metrics?: {
    enabled?: boolean;
    port?: number;
  };
  audit?: {
    retention_days?: number;
    hash_chain?: boolean;
  };
  reflection?: {
    enabled?: boolean;
    detection_threshold?: number;
    auto_archive_after_days?: number;
  };
  pricing?: {
    /**
     * Pricing per adapter
     */
    adapters?: {
      [k: string]: {
        models?: {
          [k: string]: {
            /**
             * Input price per million tokens (USD)
             */
            input_per_million: number;
            /**
             * Output price per million tokens (USD)
             */
            output_per_million: number;
            /**
             * Cache read price per million tokens (USD)
             */
            cache_read_per_million?: number;
            /**
             * Cache write price per million tokens (USD)
             */
            cache_write_per_million?: number;
          };
        };
        /**
         * Default model if not specified
         */
        default_model?: string;
      };
    };
  };
}


/**
 * Audit log entry for every write HOOP performs
 */
export interface AuditRow {
  /**
   * Unique audit entry ID
   */
  id: string;
  /**
   * Timestamp of the action
   */
  ts: string;
  /**
   * Actor identity (e.g., 'user:jedarden', 'hoop:agent:session-id')
   */
  actor: string;
  /**
   * Action kind
   */
  kind: "bead_created" | "stitch_created" | "config_changed" | "project_added" | "project_removed";
  /**
   * Target identifier (bead ID, stitch ID, etc.)
   */
  target: string;
  /**
   * Arguments passed to the action
   */
  args?: {
    [k: string]: unknown;
  };
  /**
   * Action result
   */
  result: "success" | "failure" | "partial";
  /**
   * Error message if result is not success
   */
  error?: string | null;
  /**
   * Schema version at time of action
   */
  schema_version: string;
  [k: string]: unknown;
}


/**
 * A single conversation within a project
 */
export interface Stitch {
  /**
   * Unique stitch identifier
   */
  id: string;
  /**
   * Project name
   */
  project: string;
  /**
   * Stitch kind
   */
  kind: "operator" | "dictated" | "worker" | "ad-hoc";
  /**
   * Stitch title
   */
  title: string;
  /**
   * Creator identity
   */
  created_by: string;
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Last update timestamp
   */
  updated_at?: string;
  /**
   * Closure timestamp if applicable
   */
  closed_at?: string | null;
  /**
   * Participant identities
   */
  participants?: string[];
  /**
   * Path to attachments directory
   */
  attachments_path?: string | null;
  /**
   * Whether the stitch is archived
   */
  archived?: boolean;
  /**
   * Archive timestamp
   */
  archived_at?: string | null;
  /**
   * Worker metadata for worker stitches
   */
  worker_metadata?: {
    /**
     * Worker name
     */
    worker: string;
    /**
     * Bead ID
     */
    bead: string;
    /**
     * Strand name
     */
    strand?: string | null;
    [k: string]: unknown;
  };
  /**
   * Parent stitch if spawned by another stitch
   */
  parent_stitch_id?: string | null;
  /**
   * Pattern ID if this stitch belongs to a pattern
   */
  pattern_id?: string | null;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * Link between a stitch and a bead
 */
export interface StitchBead {
  /**
   * Stitch ID
   */
  stitch_id: string;
  /**
   * Bead ID
   */
  bead_id: string;
  /**
   * Workspace path
   */
  workspace: string;
  /**
   * Relationship type
   */
  relationship: "created-here" | "executing" | "referenced";
  /**
   * When the link was created
   */
  linked_at?: string;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * Link between two stitches
 */
export interface StitchLink {
  /**
   * Source stitch ID
   */
  from_stitch: string;
  /**
   * Target stitch ID
   */
  to_stitch: string;
  /**
   * Link kind
   */
  kind: "spawned" | "references";
  /**
   * When the link was created
   */
  created_at?: string;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * A single message in a stitch
 */
export interface StitchMessage {
  /**
   * Unique message identifier
   */
  id: string;
  /**
   * Parent stitch ID
   */
  stitch_id: string;
  /**
   * Message timestamp
   */
  ts: string;
  /**
   * Message role
   */
  role: "user" | "assistant" | "system" | "tool";
  /**
   * Message content
   */
  content: {
    [k: string]: unknown;
  };
  /**
   * Attachment paths
   */
  attachments?: string[];
  /**
   * Token count if applicable
   */
  tokens?: number | null;
  /**
   * Tool use details if role is tool
   */
  tool_use?: {
    [k: string]: unknown;
  } | null;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * A grouping of stitches toward a goal
 */
export interface Pattern {
  /**
   * Unique pattern identifier
   */
  id: string;
  /**
   * Pattern title
   */
  title: string;
  /**
   * Pattern description
   */
  description?: string | null;
  /**
   * Pattern status
   */
  status: "planned" | "active" | "blocked" | "done" | "abandoned";
  /**
   * Pattern owner
   */
  owner?: string | null;
  /**
   * Optional deadline
   */
  deadline?: string | null;
  /**
   * Parent pattern ID for nesting
   */
  parent_pattern?: string | null;
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Last update timestamp
   */
  updated_at?: string;
  /**
   * Closure timestamp
   */
  closed_at?: string | null;
  /**
   * Aggregated progress percentage
   */
  progress_percent?: number;
  /**
   * Total cost in USD
   */
  total_cost_usd?: number;
  /**
   * Total duration in seconds
   */
  duration_seconds?: number | null;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * Membership of a stitch in a pattern
 */
export interface PatternMember {
  /**
   * Pattern ID
   */
  pattern_id: string;
  /**
   * Stitch ID
   */
  stitch_id: string;
  /**
   * When stitch was added
   */
  added_at?: string;
  /**
   * Who added this stitch
   */
  added_by?: string | null;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * Saved query for auto-including stitches in a pattern
 */
export interface PatternQuery {
  /**
   * Pattern ID
   */
  pattern_id: string;
  /**
   * Query string for matching stitches
   */
  query: string;
  /**
   * When query was created
   */
  created_at?: string;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * Learned rule or preference from operator behavior
 */
export interface ReflectionLedger {
  /**
   * Unique reflection identifier
   */
  id: string;
  /**
   * Scope: 'global', 'project:<name>', or 'pattern:<id>'
   */
  scope: string;
  /**
   * The learned rule
   */
  rule: string;
  /**
   * Why this rule was proposed
   */
  reason?: string;
  /**
   * Stitches that led to this rule
   */
  source_stitches?: string[];
  /**
   * Rule status
   */
  status: "proposed" | "approved" | "rejected" | "archived";
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Last time this rule was applied
   */
  last_applied?: string | null;
  /**
   * Number of times this rule was applied
   */
  applied_count?: number;
  /**
   * Who approved this rule
   */
  approved_by?: string | null;
  /**
   * Approval timestamp
   */
  approved_at?: string | null;
  /**
   * Archive timestamp
   */
  archived_at?: string | null;
  schema_version: string;
  [k: string]: unknown;
}


/**
 * Configuration parse error for projects.yaml hot-reload
 */
export interface ConfigError {
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * Line number where the error occurred (1-indexed)
   */
  line: number;
  /**
   * Column number where the error occurred (1-indexed)
   */
  col: number;
  [k: string]: unknown;
}


/**
 * Project configuration status for WebSocket events
 */
export interface ProjectConfigStatus {
  /**
   * True if the configuration is valid, false if there was a parse error
   */
  valid: boolean;
  /**
   * Error details if the configuration is invalid
   */
  error?: {
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Line number where the error occurred (1-indexed)
     */
    line: number;
    /**
     * Column number where the error occurred (1-indexed)
     */
    col: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
