#!/usr/bin/env bash
# Check that the committed OpenAPI spec matches what utoipa generates
#
# Per §20, all spec changes require a CHANGELOG entry.
# This CI enforces router → spec parity by regenerating and comparing.

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

echo "=== OpenAPI Spec Parity Check ==="
echo ""

# Build the generate_openapi binary with the openapi feature
echo "Building generate_openapi binary..."
if ! cargo build --bin generate_openapi --features openapi --quiet 2>&1; then
    echo -e "${RED}✗ Failed to build generate_openapi${NC}"
    echo "Run 'cargo build --bin generate_openapi --features openapi' to see errors"
    exit 1
fi
echo -e "${GREEN}✓ Build successful${NC}"
echo ""

# Generate the spec to a temp file
TEMP_SPEC=$(mktemp)
echo "Generating OpenAPI spec to ${TEMP_SPEC}..."
if ! cargo run --bin generate_openapi --features openapi --quiet > "$TEMP_SPEC" 2>&1; then
    echo -e "${RED}✗ Failed to generate OpenAPI spec${NC}"
    rm -f "$TEMP_SPEC"
    exit 1
fi
echo -e "${GREEN}✓ Spec generated${NC}"
echo ""

# Compare with committed spec
COMMITTED_SPEC="hoop-schema/openapi.yaml"
echo "Comparing with ${COMMITTED_SPEC}..."

if [ ! -f "$COMMITTED_SPEC" ]; then
    echo -e "${RED}✗ Committed spec not found at ${COMMITTED_SPEC}${NC}"
    rm -f "$TEMP_SPEC"
    exit 1
fi

# Normalize both specs for comparison (remove timestamps, etc.)
# This helps avoid false positives from auto-generated fields
normalize_spec() {
    # Remove fields that may vary between generations
    # - generation timestamps
    # - tool versions in descriptions
    sed -e '/generated/d' -e '/Generated by/d' -e '/utoipa/d' "$1"
}

if ! diff -q <(normalize_spec "$TEMP_SPEC") <(normalize_spec "$COMMITTED_SPEC") > /dev/null 2>&1; then
    echo -e "${RED}✗ OpenAPI spec has drifted!${NC}"
    echo ""
    echo "The generated OpenAPI spec does not match the committed spec."
    echo ""
    echo "To fix this:"
    echo "  1. Regenerate the spec:"
    echo "     cargo run --bin generate_openapi --features openapi > hoop-schema/openapi.yaml"
    echo "  2. Review the changes to ensure they're intentional"
    echo "  3. If changes are intentional, add a CHANGELOG entry per §20"
    echo "  4. Commit the updated spec"
    echo ""
    echo "Showing diff:"
    diff -u <(normalize_spec "$COMMITTED_SPEC") <(normalize_spec "$TEMP_SPEC") || true
    echo ""
    rm -f "$TEMP_SPEC"
    exit 1
fi

echo -e "${GREEN}✓ OpenAPI spec is up to date${NC}"
rm -f "$TEMP_SPEC"
exit 0
