-- Schema 2
CREATE TABLE IF NOT EXISTS table_2 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_2_name ON table_2(name);
