-- Schema 15
CREATE TABLE IF NOT EXISTS table_15 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_15_name ON table_15(name);
