-- Schema 8
CREATE TABLE IF NOT EXISTS table_8 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_8_name ON table_8(name);
