-- Schema 6
CREATE TABLE IF NOT EXISTS table_6 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_6_name ON table_6(name);
