-- Schema 25
CREATE TABLE IF NOT EXISTS table_25 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_25_name ON table_25(name);
