-- Schema 22
CREATE TABLE IF NOT EXISTS table_22 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_22_name ON table_22(name);
