-- Schema 14
CREATE TABLE IF NOT EXISTS table_14 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_14_name ON table_14(name);
