-- Schema 17
CREATE TABLE IF NOT EXISTS table_17 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_17_name ON table_17(name);
