-- Schema 29
CREATE TABLE IF NOT EXISTS table_29 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_29_name ON table_29(name);
