-- Schema 16
CREATE TABLE IF NOT EXISTS table_16 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_16_name ON table_16(name);
