-- Schema 12
CREATE TABLE IF NOT EXISTS table_12 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_12_name ON table_12(name);
