-- Schema 26
CREATE TABLE IF NOT EXISTS table_26 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_26_name ON table_26(name);
