-- Schema 21
CREATE TABLE IF NOT EXISTS table_21 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_21_name ON table_21(name);
