-- Schema 30
CREATE TABLE IF NOT EXISTS table_30 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_30_name ON table_30(name);
