-- Schema 27
CREATE TABLE IF NOT EXISTS table_27 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_27_name ON table_27(name);
