-- Schema 5
CREATE TABLE IF NOT EXISTS table_5 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_5_name ON table_5(name);
