-- Schema 28
CREATE TABLE IF NOT EXISTS table_28 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_28_name ON table_28(name);
