-- Schema 3
CREATE TABLE IF NOT EXISTS table_3 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_3_name ON table_3(name);
