-- Schema 4
CREATE TABLE IF NOT EXISTS table_4 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_4_name ON table_4(name);
