-- Schema 13
CREATE TABLE IF NOT EXISTS table_13 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_13_name ON table_13(name);
