-- Schema 18
CREATE TABLE IF NOT EXISTS table_18 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_18_name ON table_18(name);
