-- Schema 20
CREATE TABLE IF NOT EXISTS table_20 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_table_20_name ON table_20(name);
